#
# create mysql database configuration based on master-slave rule.
#
dataSources:
  ds_master: !!com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.222.16.156:3306/baitiao_test
    username: root
    password:
  ds_slave0: !!com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.222.16.144:3306/baitiao_test
    username: root
    password:

rules:
  - !MASTER_SLAVE
    dataSources:
      db_ms:
        name: ds_master_slave
        masterDataSourceName: db_master
        slaveDataSourceNames:
          - db_slave_0