schemaName: sbtest

dataSources:
  write_ds:
    url: jdbc:postgresql://10.12.3.28:5432/sbtest?serverTimezone=UTC&useSSL=false
    username: postgres
    password: sphereEx@2021
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 128
    minPoolSize: 128
    maintenanceIntervalMilliseconds: 30000

  read_ds:
    url: jdbc:postgresql://10.12.3.182:5432/sbtest?serverTimezone=UTC&useSSL=false
    username: postgres
    password: sphereEx@2021
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 128
    minPoolSize: 128
    maintenanceIntervalMilliseconds: 30000

rules:
- !READWRITE_SPLITTING
  dataSources:
    pr_ds:
      writeDataSourceName: write_ds
      readDataSourceNames: [read_ds]