#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

######################################################################################################
#
# Here you can configure the rules for the proxy.
# This example is configuration of sharding rule.
#
# If you want to use sharding, please refer to this file;
# if you want to use master-slave, please refer to the config-master_slave.yaml.
#
######################################################################################################
dataSources:
  ds_0: !!com.zaxxer.hikari.HikariDataSource
    username: root
    password:
    jdbcUrl: jdbc:mysql://10.222.16.97:3306/baitiao_test?serverTimezone=UTC&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
  ds_1: !!com.zaxxer.hikari.HikariDataSource
    username: root
    password:
    jdbcUrl: jdbc:mysql://10.222.16.156:3306/baitiao_test?serverTimezone=UTC&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
  ds_0_slave_0: !!com.zaxxer.hikari.HikariDataSource
    username: root
    password:
    jdbcUrl: jdbc:mysql://10.222.16.97:3306/baitiao_test?serverTimezone=UTC&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
  ds_1_slave_0: !!com.zaxxer.hikari.HikariDataSource
    username: root
    password:
    jdbcUrl: jdbc:mysql://10.222.16.156:3306/baitiao_test?serverTimezone=UTC&useSSL=false
    driverClassName: com.mysql.jdbc.Driver

rules:
  - !SHARDING
    tables:
      sbtest:
        actualDataNodes: ms_ds_${0..1}.sbtest${0..1023}
        databaseStrategy:
          standard:
            shardingColumn: id
            shardingAlgorithmName: database_inline
        tableStrategy:
          standard:
            shardingColumn: k
            shardingAlgorithmName: table_inline
        keyGenerateStrategy:
          column: id
          keyGeneratorName: increment
    bindingTables:
      - sbtest

    shardingAlgorithms:
      database_inline:
        type: INLINE
        props:
          algorithm.expression: ms_ds_${id % 2}
      table_inline:
        type: INLINE
        props:
          algorithm.expression: sbtest${k % 1024}
    keyGenerators:
      increment:
        type: INCREMENT

  - !MASTER_SLAVE
    dataSources:
      ms_ds_0:
        name: ms_ds_0
        masterDataSourceName: ds_0
        slaveDataSourceNames: [ds_0_slave_0]
        loadBalancerName: roundRobin
      ms_ds_1:
        name: ms_ds_1
        masterDataSourceName: ds_1
        slaveDataSourceNames: [ds_1_slave_0]
        loadBalancerName: roundRobin
    loadBalancers:
      roundRobin:
        type: ROUND_ROBIN