######################################################################################################
#
# Here you can configure the rules for the proxy.
# This example is configuration of sharding rule.
#
# If you want to use sharding, please refer to this file;
# if you want to use master-slave, please refer to the config-master_slave.yaml.
#
######################################################################################################

schemaName: sharding_db

dataSourceCommon:
  username: root
  password:
  connectionTimeoutMilliseconds: 30000
  idleTimeoutMilliseconds: 60000
  maxLifetimeMilliseconds: 1800000
  maxPoolSize: 200
  minPoolSize: 200
  maintenanceIntervalMilliseconds: 30000

dataSources:
  press_test_0:
    url: jdbc:mysql://10.222.16.97:3306/baitiao_test?serverTimezone=UTC&useSSL=false
  press_test_1:
    url: jdbc:mysql://10.222.16.97:3306/baitiao_test?serverTimezone=UTC&useSSL=false
  press_test_2:
    url: jdbc:mysql://10.222.16.97:3306/baitiao_test?serverTimezone=UTC&useSSL=false
  press_test_3:
    url: jdbc:mysql://10.222.16.97:3306/baitiao_test?serverTimezone=UTC&useSSL=false

rules:
  - !SHARDING
    defaultTableStrategy:
      none:
    tables:
      sbtest:
        actualDataNodes: press_test_${0..3}.sbtest${0..1023}
        databaseStrategy:
          standard:
            shardingColumn: id
            shardingAlgorithm: database_inline
        tableStrategy:
          standard:
            shardingColumn: k
            shardingAlgorithmName: table_inline
        keyGenerateStrategy:
          column: id
          keyGeneratorName: increment

    shardingAlgorithms:
      database_inline:
        type: INLINE
        props:
          algorithm.expression: press_test_${id % 4}
      table_inline:
        type: INLINE
        props:
          algorithm.expression: sbtest${k % 1024}

    keyGenerators:
      increment:
        type: INCREMENT